# Generated by Django 4.0.5 on 2022-06-24 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todoentry',
            old_name='todo_titel',
            new_name='titel',
        ),
    ]
