# Generated by Django 4.0.5 on 2022-06-24 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_rename_todo_titel_todoentry_titel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todoentry',
            old_name='titel',
            new_name='todo_titel',
        ),
    ]
